# Generated by Django 2.2.7 on 2019-11-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group_name',
            field=models.TextField(default='text'),
        ),
    ]
